spring.application.name=todolist

# Server Configuration
server.port=${PORT:8080}

# MySQL Configuration
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:todolist_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:todolist_password}
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Inicialização do banco
spring.sql.init.continue-on-error=true
spring.sql.init.mode=never

# Logging
logging.level.root=INFO
logging.level.br.com.aghiot=DEBUG