spring.application.name=todolist

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=todolist_user
spring.datasource.password=todolist_password
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.root=INFO
logging.level.br.com.aghiot=DEBUG